# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'MosipInjiFaceSdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMLKit/FaceDetection', '3.2.0'
  pod 'TensorFlowLiteSwift', '2.10.0', :subspecs => ['CoreML', 'Metal']

  # Pods for MosipInjiFaceSdk

end
